### ISSUE TITLE
device_from_request exception on python 3.4.3

### ISSUE THREAD

**Issue by tazogil** [stephenmcd/mezzanine#1686]
Running mezzanine 4.2.2, Django 1.10.1
mezzanine.mobile in INSTALLED_APPS. 
DEFAULT_DEVICE='mobile'

```
> python3.4/site-packages/mezzanine/utils/device.py(32)device_from_request()
 except (AttributeError, UnicodeDecodeError, UnicodeEncodeError) as e:
     31    import ipdb; ipdb.set_trace()  # XXX BREAKPOINT
---> 32    pass
ipdb> e
AttributeError("'str' object has no attribute 'decode'",)
ipdb> user_agent
'mozilla/5.0 (iphone; u; cpu iphone os 3_0 like mac os x; en-us) applewebkit/528.18 (khtml, like gecko) version/4.0 mobile/7a341 safari/528.16'
```

so the routine return "" instead of 'mobile'

**Comment by bartromgens** [comment]
This exception breaks device detection with Python 3, if no cookie was set.

This is introduced in commit https://github.com/stephenmcd/mezzanine/commit/82441cbb7ce7f3188a80fce3d4ec66e0b589dfd6 (v4.2.0).

The user agent detection was moved into the try-block and thus skipped when `user_agent.decode("utf-8")` raises an AttributeError in Python 3.

**Comment by jerivas** [comment]
Mezzanine now requires Python >= 3.6
